Redesign
ambanum/disinfo.quaidorsay.fr pull request #111
Opened 2020-11-09 13:19 UTC by clementbiron

Difficulty estimation : 🟧🟧⬜

2020-11-09 13:40 UTC, Ndpnt commented on _includes/casestudies.html
> +<section class="casestudies">
Instead of mixing languages in the markup, use a system like in the disencyclopedia, with a _data  directory and translations inside.

Used like this in  the markup:
`{{ site.data.translations.menu.principles[page.lang] }}`

2020-11-09 13:40 UTC, Ndpnt commented on _includes/casestudies.html
> +<section class="casestudies">
If you need help ask me. :)

2020-11-09 13:44 UTC, clementbiron commented on _includes/casestudies.html
> +<section class="casestudies">
I was running out of time 😥

Jekyll collections would be an appropriate technique ?

2020-11-09 13:46 UTC, Ndpnt commented on _includes/casestudies.html
> +<section class="casestudies">
I don't think

2020-11-09 13:55 UTC, Ndpnt commented on 404.md
> +htmlTitle: 404 Not Found
why renaming `title` in `htmlTitle`?

2020-11-09 13:57 UTC, Ndpnt commented
Why having a node_module directory inside sass/vendor?

2020-11-09 13:59 UTC, Ndpnt commented on _sass/elements/inline.scss
> +p{
empty css declaration

2020-11-09 13:59 UTC, Ndpnt commented on _sass/elements/inline.scss
> +/* strong, bold{
remove commented code

2020-11-09 14:00 UTC, Ndpnt commented on _sass/components/vulnerabilities.scss
> +.vulnerabilities_title{
remove empty

2020-11-09 14:01 UTC, Ndpnt commented on _sass/components/page.scss
> +	& > h1{
Are you sure you only want to target the first descendant?

2020-11-09 14:01 UTC, Ndpnt commented on _sass/components/hero.scss
> +.hero_title{
remove

2020-11-09 14:01 UTC, Ndpnt commented on _sass/components/hero.scss
> +	@include responsiveMaxWidth($bpTabletSmall){
remove

2020-11-09 14:02 UTC, Ndpnt commented on _sass/components/casestudies.scss
> +		padding:32px 24px 24px 24px;
miss space after `:`

2020-11-09 14:05 UTC, clementbiron commented on 404.md
> +htmlTitle: 404 Not Found
`title` in front matter was user in 2 contexts :
- for HTML <title>
- for <h1> content

Looks good to me than the variable name contextualizes its use.

2020-11-09 14:26 UTC, Ndpnt commented on _config.yml
> +webserver_headers:
?

2020-11-09 14:28 UTC, Ndpnt commented on _includes/vulnerabilities.html
> +<div class="vulnerabilities">
`section`?

2020-11-09 14:56 UTC, clementbiron commented on _sass/components/page.scss
> +	& > h1{
That selector is for all `<h1>` inside `<div class="page_content"></div>`

2020-11-09 16:09 UTC, Ndpnt commented on _data/translations/actions.yml
> +anchor:
This translation key seems not enough robust to me. Maybe use `our-actions-anchor`?

2020-11-09 16:11 UTC, Ndpnt commented on _data/translations/actions.yml
> +    icon: influence
Why add icon identifier in translations?

2020-11-09 16:11 UTC, Ndpnt commented on _data/translations/casestudies.yml
> +    image-src: ../../assets/img/casestudies/cambrige.jpg
I think translations should only contain translations and not convenient variables

2020-11-09 16:19 UTC, clementbiron commented on _data/translations/casestudies.yml
> +    image-src: ../../assets/img/casestudies/cambrige.jpg
Can this be put in another file in `_data` folder ?

2020-11-09 17:34 UTC, MattiSG requested changes
I didn't try to build locally yet 🙂 

- Add newlines at the end of files.

2020-11-09 17:34 UTC, MattiSG commented on _includes/header.html
> +							<img class="header_langnav_flag" src="/assets/img/flags/fr.svg" alt="Passer au français">
Redundant with the text.
```suggestion
							<img class="header_langnav_flag" src="/assets/img/flags/fr.svg" alt="">

```

2020-11-09 17:34 UTC, MattiSG commented on _includes/header.html
> +							<img class="header_langnav_flag" src="/assets/img/flags/gb.svg" alt="Switch to English language">
Redundant with the text.
```suggestion
							<img class="header_langnav_flag" src="/assets/img/flags/gb.svg" alt="">

```

2020-11-09 17:34 UTC, MattiSG commented on 404.md
> +htmlTitle: 404 Not Found
`title` is both clearer (“HTML title” could be any title since they are all in HTML; “header” or “contentHeader” would be more appropriate for an `h1`) and a standard variable in Jekyll, that will be generated in any case. It is thus important to set it properly.
```suggestion
title: 404 Not Found
```

2020-11-09 17:34 UTC, MattiSG commented on _pages/en/facebook-ads-library-assessment.md
> -numbered_headers: true
Why remove the numbered headers and the table of contents?

2020-11-09 17:34 UTC, MattiSG commented on _sass/components/actions.scss
> +.actions{
Missing spaces before brackets.

2020-11-09 17:34 UTC, MattiSG commented on _sass/components/page.scss
> +	& > h1{
> Only those _immediately_ inside the `div`, not _all_ `h1` inside a `.page_content`. I'm not sure that's what we want indeed.

2020-11-09 17:34 UTC, MattiSG commented on _sass/elements/fonts.scss
> +	src: url('./../../assets/fonts/Marianne-Regular.woff2') format('woff2'),
```suggestion
	src: url('../../assets/fonts/Marianne-Regular.woff2') format('woff2'), 

```

2020-11-09 17:34 UTC, MattiSG commented on _sass/elements/links.scss
> +	text-decoration:none;
```suggestion
	text-decoration: none;
```

2020-11-11 08:21 UTC, clementbiron commented on _pages/en/facebook-ads-library-assessment.md
> -numbered_headers: true
mistake !

2020-11-18 15:16 UTC, merged